### ISSUE TITLE
consider merging components from lopnor/p6-plackdo

### ISSUE THREAD

**Issue by softmoth** [tokuhirom/p6-Crust#32]
There is some good work done in [p6-plackdo](https://github.com/lopnor/p6-plackdo). It is old, but may still have useful code.

Unfortunately, it does not say what license it is under. Maybe the author would still be available.

**Comment by tokuhirom** [comment]
i sent fb msg to the author.

**Comment by tokuhirom** [comment]
He added a license term.

**Comment by tokuhirom** [comment]
@softmoth Which component is needed?

**Comment by softmoth** [comment]
Perhaps ::Middleware::Auth and ::Middleware::Static are useful, and not yet in Crust.

Mainly, I was impressed by how much work went into it and wanted to let you know about it, since the two projects are very similar. Thank you very much for your efforts.

**Comment by tokuhirom** [comment]
@lestrrat san ported ::Static!

**Comment by softmoth** [comment]
Thanks to both of you. I feel better knowing we've taken some small piece of the old code into the future.
