### ISSUE TITLE
p6sgi.url_scheme vs p6sgi.url-scheme

### ISSUE THREAD

**Issue by retupmoca** [tokuhirom/p6-Crust#63]
In the PSGI module and in the P6SGI document, the name %env<p6sgi.url-scheme> is used to refer to 'https' vs 'http'. Crust uses the name 'p6sgi.url_scheme'. This causes, at the very least, $crust-request.secure to not work when used with the SCGI module.

I would like to see Crust use (or at least support) the 'p6sgi.url-scheme' name, since it's used in a couple of other modules. (or have everyone standardize on the url_scheme name)

**Comment by tokuhirom** [comment]
:+1:

**Comment by tokuhirom** [comment]
```
    C<p6sgi.url-scheme>      | C<< Str:D >>                           | Either "http" or "https".
```
ref. https://raw.githubusercontent.com/zostay/P6SGI/master/P6SGI.pod
